import { signIn } from "next-auth/client";
import Head from "next/head";
import Image from "next/image";

function Login() {
  return (
    <div className="grid place-items-center">
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://links.papareact.com/5me" />
      </Head>
      <Image
        src="https://links.papareact.com/t4i"
        height={400}
        width={400}
        objectFit="contain"
      />
      <p
        onClick={signIn}
        className="p-5 cursor-pointer text-center rounded-full bg-blue-500 text-white"
      >
        Login with Facebook
      </p>
    </div>
  );
}

export default Login;
